name: Add Secret to New Repo

on:
  create:
    types: [repository]

jobs:
  add-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
      
      - name: Set secrets for new repo
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          new_repo_name="${{ github.event.repository.name }}"
          secrets=("AAA" "BBB")
          for secret in "${secrets[@]}"; do
            secret_value=$(gh secret list -R $REPO_NAME --json name,value | jq -r ".[] | select(.name==\"$secret\") | .value")
            echo "Adding secret $secret to $new_repo_name"
            echo $secret_value | gh secret set $secret -R $new_repo_name
          done

      - name: Confirm secrets
        run: gh secret list -R ${{ github.event.repository.name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

